import json
P = "gen_art_experiment"
review = {
"overall_assessment": (
"Iteration 2 ran five artifacts. Each one wrote real, audited outputs, and I recomputed or looked up every headline number I could; the itemised list is in notes/recomputed_numbers.md. Several headlines reproduce exactly: classifier F1 0.818 and AUC 0.888 (recomputed from the 300 test predictions), Gate A 17.3% of 724 edges, synthetic FDR 0.209, main-pool E_up closure S = -0.837 [-1.26, -0.427] with Holm p 0.003, and MeSH SENS1 closure -0.419 with Holm p 0.039. "
"Even so, the record cannot stand as written. It fails on four counts. "
"(1) One headline table has no source. Table 15 ('MDE (Cohen's d)': 1.22 / 0.89 / 0.64 / ...) appears in no output file. The artifact's MDEs are delta-AUC values in results/power/h1_mde.json and decisions.json: 0.134 and 0.116 at n_min 30, and 0.034-0.042 projected at n_min 5/10. The report's values even run in the opposite direction with n_min. The dead-end conclusion rests on this table, so results_reported is false. "
"(2) Conclusions contradict the artifacts. gate_A_verdict.json reads 'FAIL -> graft fallback supplies H1/H2 labels in iteration 3', and the strategy's pre-fixed decision rule (a) says the same. The report instead declares the viability layer a 'definitive' dead end and never mentions the 2,347 graft events. It explains the 55%-vs-17% gap as 'pooling vs edge granularity', but on the same 724 edges the any-parent share is 0.48 (64% >= 0.40), so the gap is definitional: the very defect the last review raised. It calls MeSH pattern frequencies 'similar', but they are early bridging 0.59 vs 0.76 and incubation->expansion 0.17 vs 0.00. It calls E_up 'adequately powered', but the artifact labels it a pilot (n = 21 < 30). "
"(3) Many numbers are wrong or mix estimators. Table 9 gives P/R/accuracy of 0.812/0.824/0.843; the artifact has 0.759/0.886/0.780. The majority-baseline F1 is given as 0.000; it is 0.715. A 'unigram-frequency' baseline appears that does not exist. The classifier is credited with LLM-A's human-anchor kappa (0.56; the classifier's own is 0.41). Table 17 pairs event-study S values with pooled-panel Holm p-values. Table 18 silently reports the secondary HGB model instead of the pre-registered logistic model. The shuffle numbers blend the E_alt and MeSH runs. A MeSH E_cent participation effect is attributed to SENS1. "
"(4) The 'replicated closure reversal' goes beyond the evidence. The MeSH artifact's own verdict is 'directional, not confirmatory'. On the main-pool-aligned block the E_up closure effect is -0.185 [-0.50, 0.11] (n = 51, n.s.), the E and E_alt signs disagree, and heterogeneity is Q = 6.2. Only 1 of 4 plan-native MeSH labels is significant. "
"Large parts of the record are also missing. Dataset_5's headline (426/426 concepts hydrated, 462,812 works, 488,078 links) is absent, as is the fact that no analysis used the enlarged pool. The linker results, Gate B, the P1 entropy-share decomposition, and the exploratory RQ1 profile are all absent; that profile (higher novelty, new-relation rate and burst state before uptake, partly replicated in MeSH) is the actual positive RQ1 characterisation. The stable entropy-only typology and the MeSH prediction rows (two of which show precursors significantly hurting) are missing too. "
"The iteration-1 section is byte-identical to the previous report: none of the prior review's corrections were applied in place, even though exp_2's audit tables (results/audit/1a-1g) now confirm them. gen_art_dataset_2, the background network behind both RQ1 experiments, is still unrecorded. "
"RQ2 (cross-disciplinary diffusion, locally concentrated vs broadly integrated), community-role dynamics, and representative cases remain unaddressed. Coverage is therefore partial. Blocking = true because results_reported is false and soundness is 1."),
"strengths": [
"The underlying experiments are unusually well engineered. Prereg freezes are hashed before any statistic (exp_2 prereg_freeze.json 5dd16d8a...5aac; exp_1 test population 6a887fb4...5505; exp_3 spec.json hash). Each artifact has an independent re-derivation script (audit_rederive.py, audit_headlines.py) and mutation or leakage tests. The headline numbers I spot-checked (classifier F1/AUC, Gate A 0.1727, FDR 0.2088, E_up closure -0.837 with Holm 0.003, MeSH closure rows) reproduce exactly.",
"Negative results are reported rather than buried: Gate A FAIL, synthetic FDR above the limit, no precursor delta-AUC, no stable typology, and the predicted precursor signs not supported. This is the right instinct for a lab record.",
"Iteration 2 does act on the previous review's biggest methodological objection. It computes Gate A as written (within-host, non-canonical, per W1 year, both arms), computes power before opening outcomes, and replaces the topic-derived habitat with a SCImago/ASJC journal habitat.",
"The report discloses that E_alt was promoted to a full analysis after the primary label yielded only 4 onsets, and it keeps the underpowered primary label E in the tables rather than dropping it.",
"The chronology is intact: the iteration-1 section was not silently rewritten, and iteration 2 is appended as its own section."
],
"dimension_scores": [
{"dimension": "soundness", "score": 1,
 "justification": "Several conclusions contradict the run's own evidence. (a) Viability is called a 'definitive dead end', but gate_A_verdict.json and pre-registered decision rule (a) route H1/H2 to the graft fallback. (b) The 55%-vs-17% Gate A gap is explained as pooling vs granularity, but the artifact shows it is definitional (any-parent 0.48 vs within-host 0.20 on the same edges). (c) MeSH patterns are called 'similar' (0.59 vs 0.76 bridging; 0.17 vs 0.00 incubation). (d) E_up is called 'adequately powered' although the artifact labels it a pilot. (e) The closure reversal is called 'replicated' although the MeSH artifact's own verdict is 'directional, not confirmatory'. Table 15 has no source, and Tables 9, 17 and 18 contain wrong or mixed-estimator numbers.",
 "improvements": [
  "Replace Table 15 with the actual delta-AUC MDE grid from results/power/h1_mde.json (n_min 5/10/20/30 x AUC0.7/0.8 x realised/projected/N150, with realised N_c 93/91/58/38 and projected 189.7/184.7/117.6/77.5). Then rewrite the power conclusion: at n_min 30 H1 is pilot-only (MDE 0.134). At n_min 5/10 on the hydrated pool the projected MDE is about 0.04, but the synthetic FDR at n_min 5 is 0.28. State that trade-off instead of 'cannot produce reliable results'.",
  "Restate the Gate A verdict verbatim ('FAIL -> graft fallback supplies H1/H2 labels in iteration 3'). Record the graft-fallback units (2,347 host-entry events; 2,154 with >= 5 entry-year keywords; screen 1,285 / held-out 869). Strike 'definitive dead end'. The claim is not dead; its Estimator-A route is.",
  "Replace the pooling explanation with the artifact's: on the same 724 edge-years the lenient any-parent share has mean 0.477 (64% >= 0.40), against 0.204 within-host. Iteration 1's 0.552 therefore measured import, not local transmission."
 ]},
{"dimension": "presentation", "score": 2,
 "justification": "The narrative is readable and the dead-end list is explicit. But almost no table names its source file. Definitions are wrong in several places (host-weight coverage, UNDETERMINED, STRICT/SENSITIVITY tiers, 'cosine-similarity' merger, 'same indicators' in MeSH). Estimators are mixed within rows.",
 "improvements": [
  "Put 'Source: <artifact>/<file>[:key]' under every table and headline sentence. For example: exp_3 results/event_study/summary_E_up.json 'table' vs 'pooled_panel'; exp_1 results/summary.json test_primary_tF1; exp_2 results/gate_a/gate_A_verdict.json.",
  "Label every estimator explicitly: event-study S vs pooled-panel coefficient; logit (primary) vs HGB (secondary); plan-native vs main-pool-aligned MeSH block."
 ]},
{"dimension": "contribution", "score": 2,
 "justification": "All five artifacts are named. But most of their result tables are missing or replaced by prose: the dataset_5 hydration headline, the linker, Gate B, P1, origin cooling, synthetic misspecification, the exploratory RQ1 profile, balance, robustness, the entropy-only typology, the MeSH prediction and aligned block, and the reconciliation audit. gen_art_dataset_2 remains absent, and none of the previous review's corrections to iteration 1 were applied.",
 "improvements": [
  "Add the missing tables listed in the critiques, artifact by artifact, each with its source file.",
  "Apply marked in-place corrections to the iteration-1 section using exp_2 results/audit/1a-1g, and add the gen_art_dataset_2 subsection."
 ]}
],
"critiques": [
{"category": "evidence", "severity": "major",
 "description": "Table 15 ('Minimum detectable effects', MDE in Cohen's d: 1.22 / 0.89 / 0.64 / 0.53 / 0.72 / 0.51 / 0.42 / 0.44 / 0.36) has no source. No such values or units exist in gen_art_experiment_2/results/power/ (h1_mde.json, h1_power_curves.csv, decisions.json, projection.json). The artifact's MDEs are delta-AUC under the pre-registered selection-rule pipeline. At AUC 0.70 realised they are 0.070 (n_min 5), 0.073 (10), 0.100 (20) and 0.134 (30); at 0.80, 0.050 / 0.054 / 0.092 / 0.116. Projected (hydrated pool) values are 0.039 / 0.042 / 0.065 / 0.084, and the N150 design gives about 0.04-0.06. The report's MDE falls as n_min rises, while the artifact's rises, because fewer concepts clear a higher n_min. The report's sentence 'the MDE at n_min = 10 and AUC = 0.7 is 0.89 SD' is the basis for 'confirms that the viability decomposition cannot produce reliable results', so a headline conclusion rests on a number no artifact produced. The delta-R2 MDEs (>= 0.03, so Maillart's 0.018 is undetectable) and Gate B (FAIL: 0 labelled episodes; about 70 clusters needed for MDE <= 25%; CRV1 size 0.16 corrected to 0.07 by wild-cluster bootstrap) are also missing.",
 "suggested_action": "Delete Table 15. Insert the n_min x AUC-target x design grid from h1_mde.json (key 'MDE'), in delta-AUC units, with realised/projected N_c from decisions.json (93/91/58/38 realised; 189.7/184.7/117.6/77.5 projected), plus the r2 rows. Add a Gate B paragraph from results/power/gate_b.json. Rewrite the conclusion: 'H1 is pilot-only at n_min 30 (MDE 0.134). A powered design needs n_min 5/10 on the hydrated 366-concept pool (MDE about 0.04), where synthetic FDR worsens to 0.28 (synth_results.json correct.n_min_5).'"},
{"category": "rigor", "severity": "major",
 "description": "The viability dead-end conclusion contradicts both the artifact and the pre-registered decision rule. gate_A_verdict.json says 'FAIL -> graft fallback supplies H1/H2 labels in iteration 3'. graft_fallback_summary.json lists 2,347 host-entry events (2,154 with >= 5 entry-year keywords; screen 1,285, held-out 869). Strategy gen_strat_1 fixed decision rule (a) in advance: 'If Gate A FAILS, H1/H2 run with graft labels computed from the new exact profiles'. Dataset_5 bought exactly those profiles: 5,488 profiles, 78.7% of host weight. The report never mentions the graft route. It declares the dead end 'definitive for the current dataset' and moves the paper to the closure result, which silently abandons a pre-registered path. The report's explanation of the Gate A drop is also wrong. It attributes 55.18% -> 17.3% to 'pooling all subfields per concept' versus edge granularity. But on the same 724 edges the lenient any-parent share is mean 0.477 with 64% >= 0.40. The drop is definitional (any-parent parents counted import), which is exactly what the previous review raised, and exp_2 states 'iteration 1's 0.552 overstated host transmission'.",
 "suggested_action": "Rewrite 'Consequence for the hypothesis' and dead end #1. Say that Estimator A (within-host lineage) is blocked, and that per pre-registered rule (a) H1/H2 move to graft labels built from the dataset_5 nativeness profiles, with the event counts above. Replace the pooling explanation with the same-edge comparison (within-host 0.204 vs any-parent 0.477; 17.3% vs 64.2% >= 0.40) and the by-year table results/gate_a/gate_a_by_arm_fold_year.csv (main screen 2010-2014 within-host means 0.20/0.28/0.23/0.19/0.20; reference 0.12-0.13). If the run chooses NOT to pursue the graft route, record that as a decision with its reason."},
{"category": "evidence", "severity": "major",
 "description": "Many reported numbers do not match the artifacts or mix estimators. Recomputed: (a) Table 9 gives precision 0.812, recall 0.824, accuracy 0.843. From exp_1 results/d2_test_predictions.json (TP 148, FP 47, FN 19, TN 86) they are 0.759, 0.886 and 0.780; only F1/AUC match. (b) 'Majority-class baseline F1 0.000' is 0.715 (predict-all-positive). 'Unigram-frequency baseline 0.689' does not exist; the lexical baselines are C-value 0.716 and lexical-only 0.762. The report also omits that LLM-A beats the classifier (0.901, delta -0.083 [-0.128, -0.041]; circular). (c) 'Against human anchors the classifier achieves kappa 0.56' is LLM-A's number; the classifier's E1 values are kappa 0.41, F1 0.674, AUC 0.84 (E2 F1 0.706). (d) Table 17 labels S = -0.837 as the 'pooled panel coefficient', but it is the event-study S; the pooled panel gives -0.743 [-1.06, -0.46]. Its Holm p-values for accretion (0.272) and participation (0.782) are pooled-panel values, whereas the event-study Holm values are 0.18 and 0.824. E_alt closure 'Holm p = 0.096' is the pooled-panel p; the event-study Holm is 0.504. (e) Table 18 reports the SECONDARY HistGB model without saying so. The pre-registered primary L2-logit gives E_up 0.890 -> 0.879 (delta -0.010 [-0.045, 0.021]), E_alt +0.051 [0.000, 0.132] and E -0.028 [-0.094, 0.019] (results/prediction/summary.json). (f) The 'shuffle mean -0.015, SD 0.082' for E_up is a blend: the main-pool shuffle exists only for E (-0.021 +/- 0.127) and E_alt (-0.019 +/- 0.082), and -0.015 is the MeSH label permutation. (g) MeSH 'participation dP significant for SENS1 (D = 0.051, CI [0.014, 0.087], Holm 0.015)' is the E_cent row. SENS1 dP is 0.010 [-0.029, 0.051], Holm 1.0 (rq1_effects.csv). (h) MeSH matching '83.3% at the 30% caliper (72.2% at 20%)' is 72.2% at 30%, 38.9% at 20%, 83.3% any. (i) Table 13's 'Share of tested' sums to 56.8% but is labelled 100%; 73 of the 169 tested edges are UNDETERMINED, and UNDETERMINED is not 'not meeting tracing density': reason codes are below_nmin 65.6%, no_cohort_parents 12.7%, tested 21.7%. The 94-99% agreement is across the EB / REF_BOOT / past-L3 / 3-reference / CANON_W1 sensitivities, not 'varying thresholds'. (j) Artifact 5 misdefines coverage. 78.7% is the share of host co-occurrence WEIGHT covered by the top 1,372 legacy-concept nodes (5,488 = 1,372 x 4 blocks), not 'the fraction of edges with all four blocks'. 12.1% is the share of concept-work LINKS covered, over 22,970 venues, of which 2,929 are covered and 37 are not citation-independent.",
 "suggested_action": "Correct each number in place with the value and file named above. Split Table 17 into two estimator blocks: event-study S/CI/Holm from summary_E_*.json 'table', and pooled-panel coefficient/CI/Holm from 'pooled_panel'. Make Table 18 show logit (primary) and HGB (secondary) side by side for E / E_alt / E_up, with n_test, positives and origins. Replace Table 9 with exp_1's full classifier table (primary, ablations, all baselines including LLM A/B) and the human-anchor table (E1/E2, classifier vs LLM A vs LLM B)."},
{"category": "evidence", "severity": "major",
 "description": "The 'replicated closure reversal' goes beyond what the MeSH artifact supports. (1) The artifact's own replication verdict is 'the open neighbourhood before emergence reading gains directional, not confirmatory, support'. (2) The report says the MeSH replication 'uses ... the same indicators'. The plan-native MeSH block uses different operationalisations (closure_lr, accretion_share, dP). The like-for-like test is the main-pool-aligned block (replication_verdict.json 'mainpool_aligned'), which the report omits. There, E_up closure is -0.185 [-0.498, 0.108], Holm 0.21, n = 51 (not significant), against main -0.837. The IVW pooled estimate is -0.41 (SE 0.125) with heterogeneity Q = 6.16. Under E and E_alt the MeSH closure sign is POSITIVE (+0.487, +0.081; sign_agree = false). (3) Among plan-native labels, only SENS1 (1 of 4: PRIMARY -0.086, Holm 0.677; SENS2 Holm 0.124; E_cent Holm 0.486) reaches significance. (4) The main-pool effect rests on E_up, a label promoted after the primary yield was seen, with n = 21 matched (51% match rate). The artifact calls it 'pilot < 30'; the report calls it 'adequately powered'. The statement 'Both populations and both label definitions point in the same direction' is contradicted by the aligned block. Under strategy rule (c), RQ1 counts as CONFIRMED only if a pre-named precursor has an event-study CI excluding 0 AND a delta-AUC CI excluding 0 AND keeps its sign on MeSH. Closure fails the predicted sign and the delta-AUC condition, and the report never evaluates rule (c).",
 "suggested_action": "Add the aligned-block table (9 rows: E/E_alt/E_up x accretion/closure/P_rar, with S_mesh [CI], n, Holm, S_main, sign_agree, IVW and Q) from replication_verdict.json or side_by_side_mainpool_vs_mesh.csv. Restate the finding as 'lower closure before sustained uptake: significant in one main-pool post-hoc label (n = 21), same sign but not significant on the like-for-like MeSH test, heterogeneous (Q = 6.2), sign-inconsistent under E/E_alt'. Evaluate the pre-registered rule (c) explicitly and record the verdict (NOT confirmed). Call E_up a pilot. Budget iteration 3 on SAMPLES (the hydrated 366-concept pool and the sealed held-out fold), not on new closure variants."},
{"category": "evidence", "severity": "major",
 "description": "Artifact 5 (art_eR1Z7fMlOcxs) is reported without its headline, and no one records that the enlarged panel went unused. The artifact hydrated the WHOLE frame: K = 426/426 concepts (366 main: screen 247 / held-out 119; 60 reference), with an exact u-order prefix, 462,812 works and 488,078 links. Hydration was iteration 2's first priority because it fixes the panel defect. The report never states these counts. Its Artifacts 7-9 still describe a 184-concept pool: exp_2 and exp_3 ran on the iteration-1 corpus in parallel. The report therefore never says that every RQ1 and viability number comes from the half-size panel, or that the power projections assume a pool which now exists. Also missing from Artifact 5: route counts A = 46 / B = 380 (retrieval route is a timing artefact and must be a covariate); sense_check_fail 45; the host traced share (lenient) 0.544 on 90,406 host c-papers; batch-equivalence attempt 1 FAILED (the list endpoint truncates authorships at 100), with the fix and a pass on attempt 2; nativeness coverage 78.7% against the strategy's >= 90% expectation (95% would need 7,584 nodes; 2,073 profiles truncated at top-200); the ASJC uncovered-reasons table (multi_subfield 38.5%, repository/arXiv 16.3%, general_only 11.3%, ...), which shows the habitat cannot serve physics/CS; and the credit ledger by step (P1 1,416, P2 5,488, P3 329, checks 4), with one key-holder as designed.",
 "suggested_action": "Rewrite the Artifact 5 subsection from gen_art_dataset_5/README.md and run_ledger.json with the counts above in a table. Add one sentence to Artifacts 7-8: 'run on the iteration-1 184-concept corpus; the 426-concept hydrated corpus was not yet used'. Add a shortfall entry: 'nativeness coverage 78.7% < 90% target'."},
{"category": "evidence", "severity": "major",
 "description": "Result tables inside executed artifacts are missing, including the positive RQ1 characterisation. Exp_3 (art_mbFjmo5rbbf8): (1) The exploratory BH q < 0.05 rows: before sustained uptake, novelty +0.156, new-relation rate +0.128, within-module z +0.073 and burst state +0.171 are higher. Under E_alt, subfield count +1.68 and nestedness is lower (replacement, not accretion). The artifact's verdict is that emergence is characterised by 'open, novel, fast-renewing neighbourhoods', and MeSH replicates burst and new-relation rate (BH q < 0.1). (2) Primary-E accretion S -0.104 [-0.120, -0.016], Holm 0.003 (pilot). (3) Accretion is 'untested, not refuted' (rarefied Baselga NA for 55% of pre-2016 rows; MDE 1.4-2.1 SD), whereas the report says 'no significant difference'. (4) Balance SMDs (0.80/0.06/0.27; entropy H 0.49-0.96 residual confound). (5) Centrality-gain delta-R2 -0.15 (HGB -0.19 [-0.31, -0.05]: precursors hurt). (6) Incubation->expansion 0%: concepts are 'born expanding'. (7) The typology used only 59 of 123 concepts (survivor bias), and an entropy-only typology IS stable (Jaccard 0.95, AMI 0.14 vs network). (8) Robustness: Leiden AMI 0.62-0.63; 63-79% of neighbourhoods denser than the degree-preserving null; reference-arm E rate 6% (coverage drift); sensitivity grid (gain threshold binding). Exp_2: the P1 decomposition (pooled entropy share SOURCE 1.4%, SINK 0.4%, UNDETERMINED 70.4%, ORIGIN 27.6%), which is the direct empirical answer to 'occupancy vs integration' at current density; origin cooling onsets 33/51/83 of 184 at theta 0.6/0.7/0.8; rho~ vs momentum Spearman 0.14; rho0 levels L1-L4; rho~ CI coverage 0.77; misspecification FDR 0.20-0.37. Exp_1: the whole NIL-aware linker (MiniLM tau 0.95; in-KB recall 0.404; main arm LINKED_EXACT 39 / BROADER 15 / UNLINKED 312); 388/426 accepted; covariate-shift AUC 0.996 triggered its rule; merger MeSH OOF AUC 0.75 missed the > 0.9 sanity target; the F9 sense-proxy failure (kappa 0); Fisher p 0.025; the population sha256. Exp_4: prediction (rolling delta-AUC +0.041 [-0.050, 0.098]; grouped-CV +0.002; E_vol -0.009 [-0.016, -0.003] and E_cent -0.036 [-0.061, -0.015], where precursors significantly HURT); participation LEVEL +0.37 SD (BH q < 0.001); and patterns, which the report calls 'similar' although early bridging is 0.59 vs 0.76 and incubation->expansion 0.17 vs 0.00 (the artifact calls this 'a genuine between-population difference').",
 "suggested_action": "Add, per artifact, the tables named above with source paths. Exp_3: results_summary.json verdicts / patterns / typology / robustness. Exp_2: results/p1/p1_summary.json, results/origin/origin_summary.json, results/synth/synth_results.json. Exp_1: README sections 3-4, results/link_calibration.json. Exp_4: rq1_prediction.csv, rq1_patterns.csv, analysis_summary.json. Replace 'Pattern frequencies ... are similar' with the actual contrast. Rewrite the RQ1 'what we learned' so it leads with the replicated exploratory profile (burst, new-relation rate, novelty), labelled exploratory, rather than with closure alone."},
{"category": "methodology", "severity": "major",
 "description": "The record is not corrected, and gen_art_dataset_2 is still missing. The iteration-1 section is byte-identical to the previous report (diff: only a separator added). None of the prior review's 12 critiques are fixed in place or acknowledged. The section still says 'This passes Gate A', '26 native / 180 S2 ... Two concepts entered through both routes', 'systematically assembled', 'The current 184 are sufficient', the 'pre-period' 'citation-independent' venue habitat, and the 214,798-link match-evidence mix, which is really the main-arm 121,829. Exp_2 has now produced reconciliation tables confirming the corrections: results/audit/1a_match_evidence.csv (all-links oa_abstract 98,192 / oa_title 92,043 / s2_only 21,509 / oa_index_only 3,054), 1b routes 24/160 and 2/20, 1c sense flags, 1e fold x F-band, and 1f eligible units by fold x year. The pre-registration (exp_2 prereg_freeze.json, which copies the gen_strat_1 selection rule verbatim) is still not reproduced. gen_art_dataset_2 (the 259,716-work design-weighted background sample) is the substrate of BOTH RQ1 experiments' co-occurrence networks. It is still absent from the record, so the network behind every RQ1 number is untraceable. Its calibration result (TV 0.41-0.79) is also why exp_4 excludes concept-discipline indicators.",
 "suggested_action": "Under each wrong iteration-1 sentence, add a marked '[Correction, iteration 2: ...]' note citing exp_2 results/audit/*. Add an iteration-1 subsection for gen_art_dataset_2 (design, 1,260 strata, weights summing to 149,116,575, the calibration_by_decile table, the T14423 low-confidence-topic and ancestor hazards, and the worker's timeout-'failed' status). Insert the pre-registered screen from prereg_freeze.json with its hash and freeze time (2026-09-28T20:55:33Z). In the iteration-2 Strategy section, list each prior critique and how this iteration addressed it."},
{"category": "clarity", "severity": "major",
 "description": "The reasoning behind iteration 2 is only partly recorded. The Strategy section omits: the R1-R5 defects the iteration was built to repair; the principle 'samples before metrics / one OpenAlex key-holder'; the pre-fixed decision rules (a)-(d) for iteration 3, including (c) 'RQ1 CONFIRMED only if ... CI excluding 0 AND delta-AUC CI excluding 0 ... keeps its sign on MeSH ... holds on the sealed held-out fold'; and the declared deviations (RQ1 run before grounding finished; MeSH run concurrently). Because the rules are missing, the report's pivot ('The paper's remaining contribution centres on the replicated closure reversal') reads as a planned outcome. It is actually a post-hoc re-reading of a pre-registered failure: the predicted sign was +. The report also mentions E_alt's post-hoc promotion but not that E_up, the only label carrying the headline, was promoted post hoc as well (results_summary.json label_note). The 'next iteration' plan (host anchoring or author overlap as non-citation proxies) ignores rule (a) and the graft route.",
 "suggested_action": "Quote the gen_strat_1 rationale and decision rules (a)-(d) in the iteration-2 Strategy section. At the end of the iteration, add a 'Decision-rule evaluation' paragraph that applies each rule to the outcomes: (a) graft fallback; (b) H1 is a pilot, since N_c = 38 < 150; (c) RQ1 not confirmed; (d) held-out fold still sealed. State the E_up post-hoc promotion alongside E_alt's."},
{"category": "novelty", "severity": "major",
 "description": "The report claims a positive, non-obvious finding: emerging concepts have lower closure and more open, bridging neighbourhoods before take-off. It names no published neighbour. The closest ones already say something very similar. Salatino, Osborne & Motta (PeerJ CS 2017, 'How are topics born?') find that new topics emerge where weakly interconnected research areas begin to cross-fertilise, with an accelerating pace of collaboration between parent areas. Chen et al. (2009) and Chen's structural-variation analysis predict transformative work from brokerage across structural holes plus burstiness, which matches this run's exploratory profile (burst state, novelty, new-relation rate). Burt's structural-holes theory and Uzzi et al. (2013) on atypical combinations are further antecedents. There is also a mechanical confound the record does not address. A concept whose top-20 association neighbourhood renews fast (high new-relation rate, novelty) will mechanically show lower closure among those neighbours. The closure reversal may restate the novelty/turnover signal rather than being a separate mechanism, and the residualisation on volume and age does not remove it.",
 "suggested_action": "Add a nearest-neighbour paragraph: cite Salatino et al. 2017, Chen et al. 2009 / SVA and Burt, and state what this run adds (per-paper, volume-matched concept-level closure against a Chung-Lu null; network-only labels; a second population). Report the within-concept correlation between closure and new-relation rate / novelty from exp_3 results/indicators/concept_year_indicators.parquet. Re-run the E_up event study with closure residualised on neighbourhood turnover, or report the partial effect in the pooled panel. Until then, grade the closure finding as 'consistent with the structural-holes literature, not yet shown distinct from neighbourhood turnover'."},
{"category": "scope", "severity": "major",
 "description": "Coverage against the user's original request is partial, and RQ2 has quietly fallen out. The request's RQ2 asks how emerging concepts diffuse across disciplinary communities, and which temporal patterns separate locally concentrated from broadly integrated concepts. It also asks for community-level roles (stay, migrate, bridge, central in expanding communities, form new clusters) and the timing of network expansion versus interdisciplinary diffusion. No executed artifact tests any of this. The concept-subfield bipartite exists (exp_3 results/concept_subfield/edges.parquet), and entropy, Rao-Stirling and subfield counts were computed, but they serve only as prediction baselines. Activity 5 (a data-derived typology) came out unstable on the network channels. The one stable typology (entropy-only, Jaccard 0.95), a diffusion-shaped typology directly relevant to RQ2, is not reported. Activity 6 (representative cases chosen from quantitative results) and the requested graphical methodology have no presence in the record, although exp_3 produced figures/methodology.png. On grounding, 312 of 366 main concepts are UNLINKED and the RQ1 analyses ran on the unfiltered pool, not on the frozen MAIN-156 population. The report's next steps (strengthen closure; non-citation proxies) do not commit to RQ2 at all.",
 "suggested_action": "Add a coverage table mapping the six requested activities and RQ1/RQ2 to done / partial / not started, with the artifact for each. Commit iteration 3 to an RQ2 analysis on the hydrated, grounded MAIN population. Candidates: diffusion trajectories of subfield entropy / Rao-Stirling from the bipartite; community-role transitions from the alluvial ids in exp_3 work/communities; expansion-vs-diffusion lead-lag; the entropy-only typology cross-tabulated with emergence labels; and 3-5 representative cases picked from those clusters. Re-run RQ1 filtered to MAIN-156 as the pre-declared 'pure filter' re-cut."},
{"category": "rigor", "severity": "minor",
 "description": "Traceability and bookkeeping are thin. No table names its output file. The hashes that make the pre-registration claims checkable are not quoted: exp_2 prereg 5dd16d8a...5aac (frozen 20:55:33Z), exp_1 population 6a887fb4...5505, exp_3 spec sha, MeSH prereg_spec features hash, frame 80e3f244...0c44. There is no run ledger per artifact (status, OpenAlex credits: dataset_5 7,237 of 8,000; LLM $: exp_1 $0.053, dataset_5 $0.024; wall time). Table 16 leaves the E_alt rate blank (it is 6.7% of 419 concept-years). The '1,487 persistent nodes' figure hides that snapshots hold about 12-13k kept nodes each.",
 "suggested_action": "Add 'Source:' lines under every table, a hashes line per artifact, and an iteration-2 run-ledger table. Fill the E_alt rate and add snapshot sizes from exp_3 results_summary.json 'snapshots'."},
{"category": "clarity", "severity": "minor",
 "description": "Several methods are misdescribed. The classifier is 'ridge LR on MiniLM and SPECTER2 embeddings', but it also uses lexical and termhood features (PCA64 each; C = 0.01). The merger 'uses cosine similarity' but is an L2 LR on 14 pair features. B-cubed 0.78 is computed on 902 held-out MeSH terms, not 'the full clustering'. STRICT is t_P90 = 0.647 plus p_merge_strict, and SENSITIVITY is the unfiltered 426-concept frame, not 'relaxing the first-appearance-year rule'. 'SINK FDR means genuine sink edges labelled as sources or vice versa' misstates FDR; the artifact's cause is that m absorbs noise citations (m CI coverage 0.62). The Baselga partition decomposes neighbourhood turnover, not community change.",
 "suggested_action": "Correct each definition from exp_1 README sections 1-2 and exp_2 README 'Synthetic validation'."}
],
"results_reported": False,
"coverage": "partial",
"blocking": True,
"score": 3,
"confidence": 4
}
with open('.terminal_claude_agent_struct_out.json','w') as f:
    json.dump(review,f,indent=1,ensure_ascii=False)
print('ok', len(review['critiques']))
