import json, pathlib
out = pathlib.Path(__file__).parent / ".terminal_claude_agent_struct_out.json"

review = {
"overall_assessment": (
"Iteration 4 did what the iteration-3 strategy promised. Four sealed folds were opened once each behind hash-checked runners. The grafting claim was replicated in a second population (MeSH). An adopter-level mechanism test was run. The run spent its budget on new samples (held-out concepts, MeSH), not on new metrics over the same panel, which is the right move. "
"I recomputed the iteration-4 headline numbers from each artifact's own files, and they match. "
"art_WZ8fbLn79nCq heldout_post.json: co-primary 1.187 [1.057, 1.335], p 0.0045, wild p 0.012, N 972, G 74; primary 0.98 [0.70, 1.37], N 250, G 30; heterogeneity p 0.25. robustness_recount.json: 20/26. "
"art_XGdzjWgi-a88 g4 README: R2 1.233 [1.117, 1.361], Holm 9.7e-5; R1 1.324; IVW 1.262 [1.173, 1.358], I² 0. "
"art_zw_JJGsUFSnd r1_holm_decisions.csv: pooled-panel closure −0.391, Holm 0.147; resT −0.109, Holm 0.635; persist −1.073, Holm 0.015. d3_table.csv: all D3 rho values. "
"art_mu0h0npvNX_u leadlag_denominator_table.csv: every Table-21 count. "
"art_FZ2OCJwV6xHs vocab_class.json: every Table-23 OR. "
"results_reported is therefore true. The iteration-1 to iteration-3 text was carried forward verbatim: my diff against gen_strat/current_report.md shows only dash normalisation, artifact-ID swaps and one marked correction. "
"The record has five defects, and they need fixing before the paper step writes from it. "
"(1) THE RQ1 HEADLINE OVERRIDES A FROZEN KILL RULE. Before opening the fold, the iteration-4 strategy fixed this rule: 'R1 is dead if the pooled-panel held-out row fails; RQ1 is then reported as structural precursors are volume/churn correlates'. The artifact returned R1_DEAD, and its reading test returned NOT_SUPPORTED (results_note.md). The report never writes R1_DEAD or the pre-declared replacement sentence. Instead, the opening summary and the methodology figure lead with 'lower persistent-neighbour closure (held-out S = −1.07, Holm p = 0.015)'. That is a secondary row: on the screen, its event-study CI included 0 (−0.575 [−1.270, 0.122]), and its held-out controls are mostly screen concepts. "
"(2) THE CRITIQUE-DISPOSITION TABLE (Table 18) CLAIMS FIXES THAT WERE NOT MADE. M2 says Holm columns and detail rows were added to the iteration-3 tables. M6 says the iteration-3 strategy was expanded. m1 says labels were corrected. The diff shows none of these changes. Items the previous review asked for are also still wrong or missing: primary CT p 0.48 (should be 0.85), '26 of 27' in the iteration-3 learned section, S_raw_cc, the Artifact-2 ID, the Granger row, and SENS2/E_cent. "
"(3) THE CAVEATS THE ARTIFACTS THEMSELVES FLAG WERE DROPPED. For grafting: the within-concept permutation p is 0.050, and CRV1 rejects 17.5% of shuffles on held-out. The pre-registered binary establishment outcome (EST_bin) is null on held-out (p 0.165). The held-out G2 Holm p values are 0.071 and 0.059. For MeSH: the analysis covers only entries from biomedicine into biomedicine, and entry-year agreement is only 50%. For the adopter test: 87% of adopters cannot be measured, and the artifact says the result cannot be separated from topical proximity. For lead-lag: the MeSH share is at the null (p 0.43), and the log-rank censoring test gives p 0.005. For rooting: raw A_cont is significantly LOWER for BROAD concepts. "
"(4) THERE ARE MISLABELS AND MIXED ESTIMATORS. E4 is the lagged-role entry-hazard test, but the report calls it an 'anchoring × typology interaction'. The PLAC and NEG controls are described wrongly. OR 3.14 is read as '3.1× more likely', although exposure prevalence is 0.79 vs 0.61. The Burt-constraint row of Table 20c mixes a pooled-panel screen value with an event-study held-out value. Table 22 mixes four models and reports m1 (3.14) instead of the pre-declared primary m2 (3.09 [2.32, 4.28]). The multi-team IRRs in Table 20 (1.14, 1.09) cannot be traced; the artifact's direct rows are 1.28 pooled and 1.19 [0.98, 1.44] held-out. "
"(5) THE CASE STUDIES EXIST BUT ARE LEFT OUT. art_mu0h0npvNX_u results/case_interpretations.md contains a full interpretation of four cases with host entries. The report marks activity 6 as 'not individually interpreted'. "
"None of this is a fabricated number, so the review is not blocking. The next report must restate RQ1 under its kill rule, correct Table 18, and transcribe the omitted caveats and case write-ups."
),
"strengths": [
"The confirmation was disciplined, and the audit trail shows it. Each sealed fold was opened once behind hash-checked runners with lock files: D2 8db17113 plus g_spec a10b7f31, R1 535c2dd3, D1 8f4bc85d and typology 695166b4. The artefact tests G1-G3 were frozen before the D2 fold was opened. MeSH mesh_spec b7cdabf8 was frozen at 07:11:10Z, before the first outcome at 07:12:10Z. Reproduction gates passed exactly: b_A 4.739106, N 1,544, G 140; 158/158 hashes.",
"Samples were added, not metrics. The underpowered screen findings were taken to new units: 93 held-out concepts with 1,097 events, 191 MeSH concepts with 2,171 co-primary events, and 100 held-out RQ1 concepts. They were not re-analysed with more indicators. The MeSH design was powered before any outcome was computed (MDE80 1.20).",
"Headline numbers trace exactly to executed outputs. I recomputed the held-out D2 rows, the MeSH R1/R2/IVW rows, all four R1 Holm rows, all IVW rows reported, the D3 table, all 24 lead-lag counts and the Table-23 vocabulary ORs, and they match their source files.",
"Dead ends are kept and labelled. Primary closure is not confirmed, D3 is null, BROAD does not anchor more, the held-out primary grafting spec is inconclusive, the held-out single-paper interaction is recorded, E4 fails, and D1 is null on both folds. The one earlier-iteration correction (the robustness recount) is marked in place with a source, and the iteration 1-3 text is otherwise unchanged.",
"Table 21 answers the previous review's lead-lag critique with the full denominator on four populations. The '94%' framing is replaced by '25 of 26 among dual-onset concepts' with its caveats."
],
"dimension_scores": [
{"dimension": "soundness", "score": 2,
 "justification": "The numbers are real and mostly recompute. The conclusions still outrun the frozen rules and the artifacts' own caveats in four places. (i) RQ1 is headlined by the persistent-neighbour row, although the pre-declared kill rule says R1_DEAD. (ii) The grafting confirmation is reported without the borderline within-concept permutation p (0.050), without the CRV1 over-rejection (17.5%), and without the null binary establishment outcome. (iii) The MeSH replication is called 'cross-domain', but it covers only entries from biomedicine into biomedicine, and entry years are measured with error. (iv) The adopter test is read as absorptive capacity. Its OR is misread as a risk ratio, and the artifact itself says the design cannot separate absorptive capacity from topical proximity.",
 "improvements": [
  "Rewrite the RQ1 line in the opening summary and in 'What we have learned' under the frozen rule. Suggested text: 'R1_DEAD under the kill rule fixed in the iteration-4 strategy (pooled-panel held-out closure −0.391 [−0.855, 0.072], Holm 0.147). RQ1 is reported as: structural precursors are volume/churn correlates. One secondary Holm-family row, persistent-neighbour closure, is significant on held-out (−1.073 [−1.858, −0.289], Holm 0.015); its screen event-study CI included 0, and its controls are 17/25 screen concepts.' Update the fig_methodology description to match.",
  "Add the missing grafting caveats to Artifact 16 as rows, with sources. They are: within-concept permutation p 0.050 (audit/audit_perm.json); CRV1 rejection 17.5% on held-out shuffles; EST_bin LPM A_cont p 0.165 on held-out (heldout_post.json EST_bin_LPM); placebo-calibrated p 0.034 (screen SD) versus 0.024 (held-out SD); and nativeness-permutation p 0.026.",
  "State the MeSH scope in Artifact 17: 'biomedicine → biomedicine entries only; 34% of partner-qualified entries removed by the coverage rule; PMID-only entry year equals the all-works year for 50% of entries (truncation_audit.json); MeSH seen before for RQ1.'"
 ]},
{"dimension": "presentation", "score": 3,
 "justification": "The iteration-4 section is clear and estimator-labelled, and the chronology holds. Several labels are wrong, though. The E4 description is wrong. PLAC is described as a 'placebo host' when it is the same host with another concept's partners. NEG is described as 'origin-subfield' when it is frequency-matched concepts. Table 20c and Table 22 mix estimators or models. The run ledger shows '-' OpenAlex credits for art_XGdzjWgi-a88, which spent 2,578.",
 "improvements": [
  "Relabel E4 as 'lagged-role entry-hazard ORs keep sign: FAIL (BRIDGE OR 0.64 screen vs 1.86 held-out)'. Add E2's ε² values (held-out 0.108 / 0.080 / 0.056) and note that E3's CI is degenerate at [1, 1].",
  "Split Table 20c by estimator. Pooled-panel constraint is +0.064 screen and +0.083 [0.002, 0.164] held-out. Event-study constraint is +0.083 screen and +0.105 [0.021, 0.187] held-out. Give the Holm decision for constraint (0.995, DEAD).",
  "In the ledger, set art_XGdzjWgi-a88 to 2,578 OpenAlex credits (logs/openalex_credit_ledger.jsonl) and art_FZ2OCJwV6xHs to 0 credits, with the note that the API pull was blocked by the credit guard."
 ]},
{"dimension": "contribution", "score": 3,
 "justification": "Every iteration-4 artifact has a section, and every headline table is present. Much of what the artifacts produced is still left out. That includes the case interpretations, the type × rooting table, the MeSH typology support, the Granger panel, the censoring test, the held-out event-study rows, the IVW row that includes 0, the adopter robustness grid, the supplementary origin-subfield check, and the MeSH R3/R4/S-rows. The reasoning behind iteration 4 (kill rules, the mechanism-label rule, what would count as DEAD) is not written into the Strategy section.",
 "improvements": [
  "Copy the strategy's 'DECISION RULES FOR THE PAPER (fixed now)' paragraph verbatim into the iteration-4 Strategy, with source gen_strat/gen_strat_1/.terminal_claude_agent_struct_out.json. Then add a 'Decision-rule evaluation (iteration 4)' table: D2 not DEAD; mechanism label host-vocabulary (pooled, partially pre-specified); G4 REPLICATED; R1_DEAD; D3 NULL, so the unifying sentence is dropped.",
  "Transcribe results/case_interpretations.md from art_mu0h0npvNX_u as a 'Representative cases' subsection, and change coverage activity 6 to 'Done (4 cases, host entries, rooted vs unrooted A_cont)'."
 ]}
],
"critiques": [
{"category": "rigor", "severity": "major",
 "description": "RQ1 HEADLINE CONTRADICTS THE PRE-DECLARED KILL RULE. The iteration-4 strategy fixed this rule before the fold was opened: 'R1 is dead if the pooled-panel held-out row fails; RQ1 is then reported as structural precursors are volume/churn correlates.' art_zw_JJGsUFSnd applied its frozen kill mapping (eval_spec.json, frozen 06:39:13Z) and got R1_DEAD. Its reading test R1-8 gave NOT_SUPPORTED. Its results_note.md says the RQ1 sentence 'becomes structural precursors are volume/churn correlates'. The strings R1_DEAD, NOT_SUPPORTED and 'volume/churn' appear nowhere in the report. Line 7 of the opening summary instead gives as the first finding 'emerging concepts have lower persistent-neighbour triadic closure than matched controls before onset (held-out S = −1.07, Holm p = 0.015)'. The fig_methodology description puts 'Held-out: persistent-neighbour closure CONFIRMED' in the emergence box. This row is one of four in the Holm family, and it is weak in three ways. (a) On the screen, its event-study estimate was −0.575 [−1.270, 0.122], with the CI including 0 (r1_event_study_screen_vs_heldout.csv). (b) The held-out 'S = −1.073' is a pooled-panel coefficient, not an event-study S; the held-out event-study S is −0.826 [−1.706, −0.096]. (c) Deviation 3 says the pre-declared fallback added 70 screen never-concepts to the pooled-panel control side, and 17/25 event-study controls are screen concepts. The body text of Artifact 18 does say 'not confirmed'. But the summary and the figure spec, which is what the paper step reads first, rescue R1 with a secondary row.",
 "suggested_action": "Replace line 7's RQ1 sentence with: 'RQ1: R1_DEAD under the pre-declared kill rule (pooled-panel held-out raw closure −0.391 [−0.855, 0.072], Holm 0.147; turnover-residualised −0.109, Holm 0.635). Structural precursors are volume/churn correlates. The persistent-neighbour closure row is significant on held-out (pooled panel −1.073 [−1.858, −0.289], Holm 0.015; event study −0.826 [−1.706, −0.096]), but its screen event-study CI included 0 and its controls are mostly screen concepts. Reading test NOT_SUPPORTED. Burt constraint again higher (+0.105 [0.021, 0.187]).' Make the same change in the 'What we have learned' heading and the fig_methodology description. Add the rows now left out: the held-out event-study rows (closure −0.534 [−1.200, 0.074]; resT −0.266 [−0.891, 0.300]); the IVW row that includes 0 (closure_resT −0.287 [−0.605, 0.032]); held-out effective size −27.8 [−49.3, −9.5] (opposite to the brokerage prediction); pooled-panel wmz +0.037 [0.006, 0.067]; the H-matched subset (n 11, resT −0.536 [−0.93, −0.13]); and balance (H SMD 0.96, not 0.94; 6 of 11 covariates with |SMD| > 0.25)."},
{"category": "evidence", "severity": "major",
 "description": "TABLE 18 CLAIMS FIXES THAT WERE NOT MADE. I diffed the iteration 1-3 text against iter_4/gen_strat/current_report.md. Apart from dash normalisation, the only changes are the artifact-ID swaps in the markers and one correction note at Table 16. Several dispositions in Table 18 are therefore false. M2: 'Additional rows incorporated into iteration-3 tables above (pooled panel, band-only matching, Holm columns)'. Table 14 still has no Holm column, and the pooled-panel sentence was already there in iteration 3. M6: 'Strategy section expanded above'. The iteration-3 Strategy is unchanged. m1: 'Corrected inline: ... Holm p precision, denominator labels'. Table 13's S_raw −0.758 is still unlabelled as S_raw_cc, and the fresh replication still has no n_matched = 14. M3 was only partly done. Table 16 still gives the PRIMARY CT p as 0.48, although d2_models_table.csv has 1.04 [0.72, 1.50], p 0.85. The iteration-3 'What we have learned' still says 'holding across 26 of 27 robustness variants' with no correction marker. The new correction note says '20 of 26 significant (excluding base row and 3 descriptive strata)'. robustness_recount.json gives 20/26 INCLUDING the base row and strata, and 18/22 excluding them. M8: Artifact 2 (line 77) is still tagged art_eR1Z7fMlOcxs, which is dataset_5's ID. M9: 'remain as reported'. The previous review noted these values are already rows in art__i2cIye01VnN results/record_of_numbers.csv, so no rerun was needed. Still missing: SENS2 (−0.858 [−1.668, 0.034]), r1a_correlations (−0.33 / −0.42), the Granger row, and the 292 MISSING_IN_REPORT count. A disposition table that misstates what was done is worse than having none: the next reviewer and the paper step will trust it.",
 "suggested_action": "Rewrite Table 18 with three columns: 'claimed', 'actually done (line numbers)' and 'still open'. Then make the corrections in place, each with a '[Correction, iteration 4: ... source: ...]' marker. Line 477: CT 1.04 [0.72, 1.50], p 0.85. Line 486: '20 of 26 including the base row and strata; 18 of 22 excluding them'. Line 551: correct '26 of 27'. Table 13: label the value S_raw_cc. Line 432: n_matched 14. Line 77: use the workspace path iter_1/gen_art/gen_art_dataset_2. Transcribe the MISSING_IN_REPORT rows for exp_1-exp_4 from record_of_numbers.csv, marked '[Added in iteration 4]'."},
{"category": "evidence", "severity": "major",
 "description": "GRAFTING CONFIRMATION: THE ARTIFACT'S OWN CAVEATS ARE LEFT OUT. The art_WZ8fbLn79nCq README lists 'Caveats the paper must carry', and the report leaves out several of them. (a) Caveat 6: 'CRV1 is anti-conservative on held-out'. Under 200 within-concept A_cont shuffles, the shuffled z has SD 1.48 and CRV1 rejects 17.5% of the time. The within-concept permutation p for the held-out headline is 0.050, which is borderline. The report gives CRV1 p 0.0045 and wild p 0.012 only. (b) heldout_post.json EST_bin_LPM: the pre-registered binary establishment outcome (iteration-1 definition) gives A_cont p 0.165 in the co-primary FE, and p 0.997 in the primary FE. The confirmed effect holds for the newcomer-paper count, not for establishment. (c) The held-out G2a Holm p values are 0.071 (NATIVE) and 0.059 (ADJACENT). The report says 'positive and significant on both folds' using unadjusted p values. (d) Table 20 gives 'multi' IRR/SD of 1.14 (pooled) and 1.09 (held-out), and neither value is in any results file. The direct G1-multi co-primary rows are 1.28 [1.11, 1.48] pooled and 1.19 [0.98, 1.44], p 0.08, held-out. The text quotes 1.28 pooled and 1.09 held-out, which is internally inconsistent. (e) G3(iii), the only citation-independent (venue ASJC) control, is degenerate on the screen (N 75, IRR 7e-16) and fails on held-out. So every working G3 control comes from OpenAlex's own classifier (caveat 4). (f) Held-out primary heterogeneity: screen b 5.95 vs held-out −0.37, p 0.17. (g) Held-out spec robustness: 7/7 rows are significant (heldout_robustness.csv), and this is also missing. (h) '83% of entry-year events are single-paper entries' cannot be traced to any file I could find.",
 "suggested_action": "Add a 'Grafting: inferential caveats' table to Artifact 16. Columns: test | held-out value | source. Rows: CRV1 p 0.0045; wild 0.012; nativeness-permutation 0.026; placebo-calibrated 0.034 (screen SD) / 0.024 (held-out SD); within-concept permutation 0.050 (audit/audit_perm.json); CRV1 null rejection 17.5%; EST_bin LPM p 0.165. Replace the Table-20 multi column with the G1-multi rows from g_*_rows.csv. Report the held-out G2a Holm p values. Add G3(iii) as 'not estimable, coverage 12%'. Give a source for the 83% figure or remove it."},
{"category": "scope", "severity": "major",
 "description": "THE MESH REPLICATION AND THE ADOPTER TEST ARE READ MORE BROADLY THAN THEIR ARTIFACTS ALLOW. MeSH (art_XGdzjWgi-a88) is described as 'a cross-domain test'. Its README caveat 1 says 'G4 speaks to biomedicine → biomedicine entries only': every entry into a non-biomedical host is dropped, and the coverage rule removes 34% of partner-qualified entries. Caveat 2: on the 13 concepts with complete retrieval, the PMID-only entry year matches the all-works entry year for only 50% of entries. Caveat 5: MeSH is not wholly unseen, since exp_4 used it. None of these appears in the report. The adopter test (art_FZ2OCJwV6xHs) has its own gaps. (a) 87% of 21,941 adopter pairs have no prior corpus work and were excluded, so the result covers adopters already active in the pool's topic space. (b) The OpenAlex exposure pull was blocked (0 credits), so exposure is corpus-only. (c) Deviation 7: 'prior use of c's partners is equally consistent with plain topical proximity', so the design does not separate absorptive capacity from topical relatedness. (d) 'Adopters are 3.1× more likely to have prior exposure' misreads an odds ratio. Prevalence is 0.79 vs 0.61, a risk ratio of about 1.3. (e) The description says controls were 'matched on publication volume'; they were exact-matched on four bins (prior works, team size, host activity, first year). (f) NEG is 'frequency-matched negative-control concepts', not 'non-partner concepts in the concept's origin subfield'. PLAC is 'partners of another concept's entry into the same host'. So the report's reading that PLAC 'confirms the effect is specific to the actual host, not to any random subfield' is wrong.",
 "suggested_action": "Artifact 17: add the three caveats verbatim and restate the verdict as 'REPLICATED for biomedicine → biomedicine host entries'. Also add the R3 (1.251), R4 (1.383), S3 placebo-host (1.031 [0.963, 1.103]), exact-only (1.243), unprofiled=1 (1.722) and S6 null (1.007 [0.69, 1.48], N 123) rows. Artifact 20: replace '3.1× more likely' with 'OR 3.09 [2.32, 4.28] (pre-declared primary m2; prevalence 0.79 vs 0.61)'. Correct the NEG, PLAC and matching descriptions. Add the coverage restriction, the zero-credit deviation and the topical-proximity limit. Add the robustness grid (1:3 matched 2.96; expanded frame 2.62; Physics 3.87; CS 3.46; single-paper 3.59 vs multi 2.33) and the post-hoc origin-subfield check (30% vs 12%; OR 2.52 [1.91, 3.43])."},
{"category": "evidence", "severity": "major",
 "description": "MISSING RQ2 DESCRIPTIVE RESULTS, INCLUDING THE CASE STUDIES THE REQUEST ASKS FOR. The original request (activity 6) asks for representative cases, with each case visualised and interpreted: network position, neighbourhood, community membership and disciplinary distribution over time. art_mu0h0npvNX_u delivered results/case_interpretations.md, cases_rooting.json and case_entries.csv for wireless backhaul, EPR steering, locally repairable code and holographic QCD. That write-up covers subfield shares from F+1 to 2022, roles, Guimerà-Amaral P, betweenness, and rooted vs unrooted A_cont per host entry (+0.062 and +0.115). The report says 'Four medoid cases selected but not individually interpreted in the report' and marks the activity Partial. Other outputs of this artifact are also missing. (a) Type × rooting: BROAD has 18.4 vs 6.6 host entries per concept and EST rate 0.31 vs 0.13. Raw A_cont is significantly LOWER for BROAD, −0.017 [−0.025, −0.010]; the report gives only the adjusted null. PPML by type: BROAD 1.36 [1.20, 1.55] vs LOCALISED 1.16 [0.98, 1.38], interaction p 0.11. (b) MeSH typology support: 12.6% of MeSH concepts are out of support, and KS p is 4e-17. The coverage table's 'k = 2 replicates on held-out and MeSH' overstates this: MeSH is an assignment to frozen medoids with poor fit and a BROAD share of 0.71 vs 0.33. (c) MeSH lead-lag: 9/13 = 0.69 against a year-shuffle null of 0.62, p 0.43. The report calls this 'directionally consistent'; the artifact finds it indistinguishable from the null. (d) Censoring: diffusion onsets are rarer than expansion onsets (log-rank p 0.005 pooled), and the F ≤ 2012 cohort has only 12 dual-onset concepts. (e) Granger panel: lagged ΔP → ΔH, b −0.0013, p 0.068 (negative). The strategy asked for this row, and so did the previous review. (f) Held-out roles: BRIDGE 0.60, seed agreement 0.976. Cross-tabs: origin V 0.28-0.30, pooled Holm 0.001; E_up held-out Holm 0.016. MeSH seed stability was not assessed.",
 "suggested_action": "Add a 'Representative cases' subsection transcribing case_interpretations.md, one paragraph per case with source lines, and set activity 6 to Done. Add a type × rooting table from results/rooting.json (occupancy, EST rate, raw and adjusted A_cont, adjusted CT, PPML by type). Replace 'k = 2 replicates on ... MeSH' with 'held-out within support (KS p 0.13); MeSH largely outside support (KS p 4e-17), assignment descriptive'. Replace 'weaker but directionally consistent' with 'not different from the year-shuffle null (0.69 vs 0.62, p 0.43)'. Add the log-rank, F ≤ 2012 and Granger rows from leadlag_table.json."},
{"category": "clarity", "severity": "major",
 "description": "ITERATION-4 REASONING AND DECISION RULES ARE NOT RECORDED. The Strategy section has two paragraphs. The strategy file contains much more: the diagnosis (D2 strong, R1 secondary, D1 closed); why each of the five slots was chosen (confirmation, replication, mechanism, closing R1/D3, the RQ2 layer); the deliberately broken principles; and the paper decision rules fixed before any look. Those rules are: D2 DEAD if the held-out co-primary CI includes 1; the mechanism-label rule; G4 success/failure; R1 DEAD if pooled-panel held-out fails; D3 null drops the unifying sentence. None of this is in the report, so a reader cannot check that the outcomes were read against pre-declared rules. That is exactly how R1 got rescued in the summary. The strategy also planned that 'Iteration 5 writes the ANS paper with no new tests', and this is not recorded. The report says the mechanism label was reached 'Combining the single-paper, vocabulary-decomposition, and topic-score tests'. It does not say that the label is 'pooled, partially pre-specified': the held-out G rows were not in the frozen heldout_spec, and the screen G rows were not blind (mechanism_label.json scope).",
 "suggested_action": "Expand the iteration-4 Strategy with the diagnosis, the slot rationale and a verbatim copy of 'DECISION RULES FOR THE PAPER (fixed now)', citing its source. Add a 'Decision-rule evaluation (iteration 4)' table: D2 kill rule not triggered (co-primary CI 1.06-1.33); mechanism label host-vocabulary (pooled, partially pre-specified; artefact conditions: G1 CI excludes 1, G3 removes −7.3%); G4 REPLICATED; R1_DEAD; D3 NULL, so the unifying sentence is dropped; D1 null. Add a 'Plan for iteration 5' paragraph."},
{"category": "novelty", "severity": "minor",
 "description": "NEAREST-NEIGHBOUR CHECK FOR THE TWO NEW POSITIVE CLAIMS. (1) Host-vocabulary grafting. The nearest published result is Cheng et al. 2023, ASR 88(3):521-561: new ideas diffuse more when linked to well-established, central constructs. The report states what it adds: a per-entry, host-specific decomposition, a co-transfer null, and a second population. That is adequate, but it should also say that its outcome (newcomer paper counts) differs from Cheng's, and that the binary establishment outcome is null on held-out. (2) Adopter enrichment. Jia, Wang & Szymanski 2017 (Nature Human Behaviour 1:0078) show that scientists' research-interest shifts are local, which predicts that adopters already work near c's partner concepts. The artifact itself concedes that the design cannot separate absorptive capacity from topical proximity. The report cites only Cohen & Levinthal 1990 and never names this neighbour, so the 'SUPPORT for absorptive capacity' reading has not earned its claim. The FOREIGN > NATIVE gradient is the only non-obvious part. Hofstra et al. 2020 (PNAS 117:9284) also measure uptake of novel conceptual links, and are the nearest neighbour for an outcome defined as 'uptake of new concept pairings'.",
 "suggested_action": "Add to the Artifact 20 reading: 'Expected under local interest drift (Jia et al. 2017); what this adds is that the enrichment is specific to c's partners over frequency-matched (NEG, 0.62) and same-host other-concept partners (PLAC, 0.72), and is carried by FOREIGN not NATIVE partners (ratio 0.51 [0.33, 0.89]).' Downgrade 'SUPPORT for absorptive capacity' to 'consistent with absorptive capacity or topical proximity'."},
{"category": "clarity", "severity": "minor",
 "description": "METHODOLOGY FIGURE AND COVERAGE AGAINST THE REQUEST. The user asks for a general methodology in graphical form, clearly explained. fig_methodology is still placed inside the Iteration-1 section, although it depicts the 426-concept pool from iteration 2 and results from iteration 4. Its caption does not show three things: the actual decision path (source-sink hypothesis → Gate A fail → graft fallback), the held-out/MeSH/adopter layers, or the dead strands. Its description encodes the rescued R1 claim and OR 3.14. Operational definitions are scattered across four iterations: E_up, A_cont, CT, Y_strict, EST_bin, persistent-neighbour closure, and the folds. There is no single 'final design as executed' block the paper step can draw the figure from. Separately, the request's 'increasing structural brokerage' trajectory type is now ruled out by evidence (constraint higher on both folds, effective size lower on held-out). This should be recorded as an answered sub-question, not left implicit.",
 "suggested_action": "Add an '[Added in iteration 4] Final design as executed' block after the iteration-4 section. It should give one line per construct with its definition and source artifact, the fold/population flow (screen 202 → held-out 100; D2 1,544 / 972 events; MeSH 2,171), and which strands are live or dead. Rewrite the fig_methodology description from that block: a decision flow with the dead branches greyed, R1 marked DEAD, and the OR shown as 3.09."}
],
"results_reported": True,
"coverage": "partial",
"blocking": False,
"score": 5,
"confidence": 4
}

out.write_text(json.dumps(review, indent=1, ensure_ascii=False))
print("wrote", out, len(review["critiques"]), "critiques")
