import json, pathlib
out = pathlib.Path(__file__).parent / ".terminal_claude_agent_struct_out.json"

review = {
"overall_assessment": (
"Iteration 3 is a real improvement to the record. The previous blocking review asked for five major things, and this iteration delivered them: the pre-registered graft fallback was executed (art_2Cd2JJypeGuA); RQ2 was executed at three scales (art_62TVG6A4f7Iy breadth screen, art_2Cd2JJypeGuA host entry, art_QKsLguxnGFQT typology/roles/lead-lag/cases); the turnover confound was tested head-on (art_htO_gJuUn6Pr, art__i2cIye01VnN); a numbers-of-record audit fixed 42 flagged values; and dataset_2, the pre-registered screen and decision rules (a)-(d) are now written down. "
"I recomputed the headline numbers from the artifacts' own files, and they match. From art_htO_gJuUn6Pr results/verdict.json: raw closure S -0.439 [-0.810,-0.050]; R1a -0.295 [-0.663,0.092]; constraint +0.083 [0.017,0.147]; xc_excess +0.063; verdict MIXED. From art_62TVG6A4f7Iy results/headline_tables.md: all four Table-15 rows. From art_2Cd2JJypeGuA results/d2_models_table.csv: co-primary IRR/SD 1.300 [1.164,1.452], p 6.4e-6, 1,544 events / 140 clusters; primary 1.386 [0.968,1.985]. From art_QKsLguxnGFQT results/leadlag.json: 15/16 = 0.9375, null 0.62, p 0.004. So results_reported is true. "
"The record still has four kinds of defect. "
"(1) CHRONOLOGY. The iteration-2 section was rewritten, not corrected in place. Whole subsections are gone: synthetic validation, snapshot construction, precursor definitions, MeSH label counts, matching, the SENS2 and E_cent rows, the event-null test. The original iteration-2 conclusions ('clear and replicated finding', 'definitive dead end', 'adequately powered') were replaced with no marker. Iteration-1 text was also changed without markers. "
"(2) COMPLETENESS. Most iteration-3 tables beyond the headline row are missing. The run's own audit artifact flags 292 of 406 audited numbers as MISSING_IN_REPORT, and the report does not mention that. "
"(3) TRACEABILITY / MISMATCHES. Iteration-3 markers use folder names, not artifact IDs. The dataset_2 background sample is tagged with dataset_5's ID. In Table 16, the primary-spec CT p is given as 0.48 but is 0.85. '26 of 27 robustness variants' cannot be recomputed from d2_robustness.csv, where 5-6 co-primary rows are null, including the only multi-paper-entry subset. "
"(4) PROPORTIONALITY. The abstract claims three things more strongly than the evidence allows. 'Significantly lower closure ... bridging positions' conflicts with the report's own Burt-constraint result (not brokerage) and with a primary turnover-residualised CI that includes 0. '94% expansion-first' rests on 16 of 202 concepts, while 39 concepts diffuse with no expansion onset, only 2 dual-onset concepts have onsets up to 2015, and the Granger-style panel points the other way. 'Grafting makes concepts stick' is read causally, but the pre-registered within-concept-year design says NEITHER, and the artifact itself limits the claim to comparisons across a concept's entries at different times and hosts. "
"None of these is a fabricated number or a headline that contradicts its artifact, so the record is not blocking. But the next iteration should restore the iteration-2 text, add the missing tables, and restate the three claims at the size the evidence supports, before opening the sealed held-out folds."
),
"strengths": [
"The previous blocking review was answered in substance, not only in prose. The graft fallback (rule a) was actually run on 4,177 host entries with exact nativeness profiles. RQ2 now has a breadth screen, a host-entry PPML, a stable k=2 diffusion typology, community roles, a lead-lag test and medoid cases. The turnover objection was tested with a verdict rule fixed before any label (prereg_v3.json 2f46d173...).",
"Negative results are kept and labelled in the iteration-3 section: openness does not predict breadth (D1_NOT_SUPPORTED_SCREEN, Holm p 0.405 for all three outcomes); the constraint sign rules out Burt brokerage; the 3-channel typology adds nothing over entropy-only after volume residualisation; lagged roles do not predict entry (BRIDGE OR 0.64 [0.38,1.08]); co-transfer is null; take-off prediction is still null (dAUC -0.001 [-0.008,0.006]).",
"Headline numbers trace exactly to executed outputs. I recomputed S, CI, IRR and lead-lag shares from verdict.json, headline_tables.md, d2_models_table.csv and leadlag.json, and they match. The report also adds 'Source:' lines, a hash table (9 hashes) and a run ledger.",
"The design is disciplined. Every iteration-3 experiment re-verifies the iteration-2 substrate before computing anything: closure r = 1.000000 in code mode, and the E_up event study reproduces bit for bit. Held-out folds are sealed behind hash-checked runners (535c2dd3, 8db17113, 695166b4). Fallbacks (F3, fallback 3, fallback 6) were declared before outcomes and are disclosed.",
"Corrections to iteration-1 and iteration-2 numbers from the audit (classifier P/R/accuracy, majority F1, MDE units, estimator pairing in the event-study table, logit vs HGB) are now marked with '[Correction ...]' notes."
],
"dimension_scores": [
{"dimension": "soundness", "score": 2,
 "justification": "Every headline number comes from an executed artifact and recomputes. The written conclusions go further than the evidence in three places. (i) 'Survives turnover controls' / 'bridging positions': the primary R1a CI includes 0, Holm 0.194; the artifact flags it underpowered and R1a_model_dependent; the audit calls it AMBIGUOUS/UNDERPOWERED; and constraint is higher, i.e. not brokerage. (ii) The grafting effect is read as an entry-mode mechanism, although the pre-registered within-concept-year spec is NEITHER and the effect disappears in multi-paper entries. (iii) The 94% lead-lag share rests on 16/202 concepts and leaves out 39 diffusion-only concepts. There are also two number mismatches: primary CT p, and '26 of 27'.",
 "improvements": [
  "Restate the closure claim as: a screened candidate on a post-hoc label; sign-consistent across cells; not reducible to turnover by the pre-declared retention rule (|S_res| >= 0.5|S_raw|); primary CI includes 0; not brokerage; held-out pending. This removes the conflict with verdict.json.",
  "Restate the grafting claim as a between-entry association (concept + e + d FE). Report the NEITHER primary, the single-paper exclusion (1.24 [0.90,1.71], p 0.17) and the null binary cut-offs next to it.",
  "Report the lead-lag denominator in full: 202 concepts = 110 neither, 39 diffusion-only, 37 expansion-only, 15 expansion-first, 1 same year. Add the Granger panel result."
 ]},
{"dimension": "presentation", "score": 3,
 "justification": "The iteration-3 section is clear, uses estimator-consistent tables and gives source lines. Two things keep this from a 4. Artifact markers for iteration 3 are folder names, so they will not resolve. The iteration-2 section was compressed and rewritten, so a reader cannot tell what the run believed at the end of iteration 2.",
 "improvements": [
  "Replace [ARTIFACT:gen_art_experiment_5/6/7/8] and [ARTIFACT:gen_art_evaluation_1] with art_htO_gJuUn6Pr, art_62TVG6A4f7Iy, art_2Cd2JJypeGuA, art_QKsLguxnGFQT and art__i2cIye01VnN. Remove art_eR1Z7fMlOcxs from Artifact 2 (dataset_2 has no artifact id in the supplement; name the workspace path instead).",
  "Tag every block inserted into earlier iterations with '[Added in iteration 3]'."
 ]},
{"dimension": "contribution", "score": 3,
 "justification": "Every executed artifact now has a section. The dead ends of iterations 2-3 are kept, and the decision rules are recorded. Still, much of the run is not preserved. Most secondary tables of the four iteration-3 experiments are missing. Several items the previous review named for exp_1-exp_4 are still absent. The audit's 292 MISSING_IN_REPORT rows go unmentioned. The iteration-3 strategy's rationale and the iteration-4 decision rules are not recorded.",
 "improvements": [
  "Add the per-artifact tables listed in the completeness critique, pulling values from results_summary.json, headline_tables.md, d2_robustness.csv, typology.json and leadlag.json.",
  "Append the MISSING_IN_REPORT rows from art__i2cIye01VnN results/record_of_numbers.csv as an appendix table, grouped by artifact."
 ]}
],
"critiques": [
{"category": "methodology", "severity": "major",
 "description": "CHRONOLOGY BROKEN: the iteration-2 section was silently rewritten, and parts of iteration 1 were too. Comparing with the previous report (iter_3/gen_strat/current_report.md, lines 224-554) shows the following. (a) Whole subsections were deleted, not corrected: 'Synthetic validation' (its FDR table), 'Co-occurrence network snapshots', 'Precursor indicators' (definitions), 'Emergence labels' for MeSH (18/34/14/42 counts table), 'Matching', and MeSH Table 20's SENS2 (-0.858 [-1.668,0.034], Holm 0.124) and E_cent (-0.148, Holm 0.486) rows. The event-null permutation check (mean 0.019, SD 0.224) is also gone. (b) The original iteration-2 conclusions were replaced without any marker. The old text said 'The precursor question yields a clear and replicated finding', 'Both populations and both label definitions point in the same direction', 'This dead end is definitive for the current dataset', and 'E_up ... Adequately powered'. The run acted on these beliefs, and they have vanished. (c) Iteration-1 text changed without markers. The reference-arm definition went from 'age >= 10 years, flat incidence, >= 30 papers/yr' to '>= 5 hits in every year 1998-2004 ...'. The target changed from '400' to '~600 (floor 400)'. A whole pre-registered-screen paragraph was inserted. 'reference concepts used to calibrate the replacement benchmark' was deleted. (d) The iteration-2 'Decision-rule evaluation' and 'Coverage' tables were written in iteration 3 but sit inside iteration 2 unlabelled. Artifacts were also renumbered (old Artifact 5 is now 6, etc.).",
 "suggested_action": "Restore the iteration-2 section verbatim from gen_strat/current_report.md lines 224-554. Correct errors in place with '[Correction, iteration 3: ... source: art__i2cIye01VnN results/record_of_numbers.csv row <id>]' notes; keep the wrong sentence, struck through or quoted. Put the deleted subsections back, fixing only their numbers (e.g. MeSH matching 72.2% at 30%, 38.9% at 20%; SENS1 dP 0.010 [-0.029,0.051], Holm 1.0). Mark every inserted block (pre-registered screen, decision-rule evaluation, coverage table) '[Added in iteration 3]'. Do the same for the unmarked iteration-1 edits."},
{"category": "evidence", "severity": "major",
 "description": "COMPLETENESS: most iteration-3 result tables are missing; only the headline rows are reported. The audit artifact (art__i2cIye01VnN results/record_summary.json) itself reports 292 of 406 audited numbers as MISSING_IN_REPORT; the report quotes the 42 drift flags and leaves this out. Specific misses by artifact follow. art_htO_gJuUn6Pr (Table 14): the Holm column (R1a/R1b 0.194, constraint 0.039); the pooled-panel table (closure_resT -0.40 [-0.70,-0.12], closure_persist -1.12 [-1.64,-0.71], extended panel -0.55 [-0.83,-0.31]); band-only matching (R1a -0.45 [-0.73,-0.18], R1b -1.32 [-1.94,-0.80]); the partial logit (-0.73/SD); H-matched (-0.75, n=7); route-B-only rows; E_alt 20 / E 7 onsets on the hydrated pool; match rate 26/68 = 38%; H SMD 0.55; prediction BASE AUC 0.854 vs FULL 0.853; the held-out MDE table (pooled 0.38/0.50/0.44 SD vs ES 0.56/0.62/0.62). art_62TVG6A4f7Iy: the secondary rows for Burt constraint, effective size and cross-community pairs (all null; ES/degree ΔR² -0.015 [-0.033,-0.004]); Table 2 (E_up subset, ΔR² significantly NEGATIVE for Y1r/Y2); the robustness grid (132 specs; co-primary Y2 CI excludes 0 in 58% of specs, opposite direction); the mediation table; the MDE table; R1a fit R² = 0.058; sanity checks. art_2Cd2JJypeGuA: CIs for the coarsenings (concept+d×e 1.22 [1.05,1.40] Holm 0.015; concept×2yr 1.10 [0.83,1.46]); the CT rows with CIs; the 27-row robustness table; the tag partition (graft 1.8%, native companion 0.9%, package 69.6%, third party 27.7%, 24% unprofiled, coverage 74%); the placebo z SDs 1.26/1.38; OOS deviance -0.23 [-0.54,0.06] with Spearman 0.419 -> 0.431; the 9 deviations. art_QKsLguxnGFQT: cross-tabs (cluster × E_up p 0.097; × closure tercile p 0.11; k=3 × E_up p 0.027; × F-band p 0.077); validation on pool-percentile gain (ε² 0.065 vs B1 0.131 vs volume 0.424); typology sensitivities (AMI 0.59 STRICT, 0.60 fixed window, 0.69 fully rarefied); BRIDGE persistence 0.80; BRIDGE 0.71 broad vs 0.56 localised; FOUNDER OR 0.43 [0.19,0.94]; 14.2% of concept-years imputed.",
 "suggested_action": "For each iteration-3 artifact, paste the full result tables with source paths: art_htO_gJuUn6Pr results/verdict.json, results/event_study/primary_family.json, results/power_mde.json, results/prediction.json; art_62TVG6A4f7Iy results/headline_tables.md Tables 1-5; art_2Cd2JJypeGuA results/d2_models_table.csv, d2_robustness.csv (all 54 rows), labels_summary.json, oos_check.json, deviations.md; art_QKsLguxnGFQT results/typology.json crosstabs, validation.json, roles.json, leadlag.json. Add one sentence to Artifact 11 stating the 292 MISSING_IN_REPORT count, and append that list as an appendix."},
{"category": "evidence", "severity": "major",
 "description": "GRAFTING: one mismatch, one number that cannot be recomputed, and fragility that is left out. (a) Table 16 gives CT p = 0.48 for the PRIMARY spec. In d2_models_table.csv, M1 primary CT is IRR 1.037 [0.717,1.500], p 0.846 (wild 0.857); 0.48 is the co-primary value. (b) 'Holds in 26 of 27 robustness variants (IRR 1.25-1.56, p <= 0.001)' cannot be recomputed from results/d2_robustness.csv. It appears only in the artifact's summary text. Among the 27 co-primary rows, the null ones are: binary native >= 0.5 (1.005, p 0.92); >= 0.7 (1.066, p 0.29); A_distinct (1.003, p 0.96); exclude single-paper entries (1.244 [0.90,1.71], p 0.17, 200 events/50 clusters); the CS stratum (1.15, p 0.11); and Physics/Astro (0.99, p 0.95). Binary >= 0.3 has p 0.007 (> 0.001). The upper bound is 2.47, outside 1.25-1.56. (c) 1,344 of the 1,544 co-primary events (87%) are single-paper entries, and the effect is not significant once they are dropped. This matters for interpretation. A spuriously classified one-off host paper would have few host-native partners AND no follow-up uptake, which gives the same association without any grafting mechanism. The topic_score >= 0.9 row (1.275) partly addresses this, but the report never states the issue. (d) The report reads the result as 'the mode of entry matters: concepts that re-contextualise ... establish more durably'. The artifact limits it: 'not identified within a concept-year ... the evidence is for grafting across a concept's entries at different times and hosts', and the pre-registered primary within-concept-year design gave NEITHER.",
 "suggested_action": "Correct the primary CT to 1.04 [0.72,1.50], p 0.85. Replace '26 of 27' with a count recomputed from d2_robustness.csv; list every null row with IRR/CI/p/N/G, and state how many events are single-paper entries. Rewrite the conclusion as: 'Across a concept's host entries (concept + year + host FE), entries whose partners are more host-native attract more author-disjoint newcomer uptake (IRR/SD 1.30 [1.16,1.45]). The pre-registered within-concept-year test is underpowered and null, the effect is absent in multi-paper entries and in physics, and OOS gain is not significant. Held-out confirmation (MDE 1.15) is pending.'"},
{"category": "rigor", "severity": "major",
 "description": "THE CLOSURE CLAIM IS STATED MORE STRONGLY THAN ITS ARTIFACTS SUPPORT. The abstract and 'What we learned' say 'emerging concepts have significantly lower triadic closure ... structurally open, bridging positions' and 'the closure effect survives turnover controls'. In art_htO_gJuUn6Pr's own terms, the primary turnover-residualised estimate is S_res -0.295 [-0.663, 0.092], Holm 0.194. The artifact carries the flags 'underpowered' (26 matched < 30) and 'R1a_model_dependent'. Match rate is 38%, with residual entropy imbalance (SMD 0.55). E_up is a post-hoc label, and the fresh 100-concept replication is n = 14 matched, CI [-1.006, 0.060]. The audit artifact's own verdict on the same question is 'AMBIGUOUS / UNDERPOWERED' (Table 13). The report cites within-concept r(closure, new-relation rate) = -0.19 (iteration-2 pool). On the hydrated pool, art_htO_gJuUn6Pr results/r1a_correlations.json gives demeaned r = -0.33 [-0.39,-0.26] with new-relation rate and -0.42 [-0.49,-0.36] with novelty. That coupling is about twice as strong and never appears in the report. 'Bridging' also conflicts with the report's own R1c row: constraint is HIGHER (+0.083) and log(n·C) +0.28, i.e. more redundant ego networks, not brokerage. Finally, rule (c) is not re-applied in iteration 3: the delta-AUC CI still includes 0 (-0.001 [-0.008,0.006]), so RQ1 is still NOT CONFIRMED.",
 "suggested_action": "Replace the headline with: 'Lower raw closure before sustained uptake (post-hoc label; S -0.439 [-0.810,-0.050], 26/68 matched). Not reducible to turnover by the pre-declared retention rule (|S_res|/|S_raw| = 0.67), but the primary residualised CI includes 0 (significant only in the pooled panel and band-only matching). Not Burt brokerage (constraint higher). Neighbours span more communities (xc_excess +0.063). Screened candidate; held-out test pending.' Add the r1a_correlations table. Add an iteration-3 decision-rule paragraph: rule (c) NOT MET; strategy rule (ii) not triggered, since the verdict is MIXED, not TURNOVER."},
{"category": "evidence", "severity": "major",
 "description": "LEAD-LAG '94%' IS DISPROPORTIONATE, AND THE COUNTER-EVIDENCE IS LEFT OUT. The abstract states 'network expansion precedes disciplinary diffusion in 94% of concepts exhibiting both transitions'. art_QKsLguxnGFQT results/leadlag.json shows that only 16 of 202 MAIN concepts have both onsets outside left-censoring. The full breakdown is 110 neither, 39 diffusion-only, 37 expansion-only, 15 expansion-first and 1 same-year. So 39 concepts diffuse with NO expansion onset at all, which weighs against 'expansion then diffusion' as a general pathway. 15 concepts diffuse from the start. Only 2 dual-onset concepts have onsets <= 2015, and 24% of onsets fall in 2016-2018, so right-censoring and evaluability are live issues. The diffusion onset needs H_rar with >= 10 papers in the window, so it mechanically comes after volume accumulation. The Granger-style panel (lagged Δpct_alt -> ΔH_rar) is p = 0.07 with a NEGATIVE sign. The artifact itself flags F7_underpowered. By cluster, broad concepts are 5/6 expansion-first with CI [0.5,1.0].",
 "suggested_action": "Add the full category-count table (primary, incl. from-start, secondary definitions all_node_pct n=2, cumulative_2yr n=8, widened n=20, all_screen_mainarm n=21) and the Granger panel row. Restate the claim as: 'Among the 16 concepts (8%) with both onsets observable, expansion came first in 15 (null 0.62, p 0.004). 39 concepts diffused without an expansion onset; the evaluability rule for diffusion onsets favours this ordering; underpowered.' Remove the unconditional 94% from the abstract framing."},
{"category": "clarity", "severity": "major",
 "description": "ITERATION-3 REASONING IS ONLY PARTLY RECORDED. The iteration-3 Strategy is one paragraph. The strategy file (gen_strat/gen_strat_1/.terminal_claude_agent_struct_out.json) contains several things the report omits. (1) The rationale: a DEEPEN iteration; samples before metrics; moving 'sideways' from the lost take-off AUC to spread (D1); D2 as the pre-registered rule-(a) fallback. (2) The verdict rules fixed before any number: BROKERAGE/TURNOVER/MIXED; D1_SUPPORTED_SCREEN; GRAFTING/TOOLKIT/NEITHER; fallbacks 3 and 6; F3 row-count rule. (3) The 'deliberately broken' principles: sign learned on the screen, parallel recomputation of closure, MeSH used only as a secondary check. (4) DECISION RULES FOR ITERATION 4 (i)-(iv): one look per frozen spec on the sealed fold, no subgroup search; if R1 = TURNOVER, only D1/D2 go forward; D3 as a join of D1 openness and D2 anchoring; held-out assignment to frozen medoids. (5) D3 was planned but is not mentioned anywhere, and there is no statement that it was deferred. (6) There is no list of the previous review's 11 critiques with how each was addressed. (7) There is no 'next steps' or iteration-3 decision-rule evaluation, so the pending held-out confirmation (4 hashed specs) and what would kill each claim are not in the record.",
 "suggested_action": "Expand the iteration-3 Strategy with a quoted rationale and the pre-declared verdict rules, each with its hash. Add a table 'Previous-review critique -> action taken -> where in the report'. Add 'Decision-rule evaluation (iteration 3)', applying R1/D1/D2 verdicts and fallbacks, and 'Plan for iteration 4', quoting rules (i)-(iv) and the four held-out spec hashes with their MDEs. Record D3 as deferred, with the reason."},
{"category": "scope", "severity": "major",
 "description": "The coverage table says 'Done' for all six activities, but parts of the request are unanswered or only nominally answered. (1) Semantic grounding (activity 1). The concept-concept network the RQ1/RQ2 analyses run on has about 27k OpenAlex LEGACY-concept nodes from the background sample, with the pool concepts attached. The grafting partners are also legacy tags (art_2Cd2JJypeGuA limitation 1; art_htO_gJuUn6Pr scope note). So the 'semantically grounded knowledge graph' is grounded only at the focal concepts, and the report never says so. Variant normalisation is minimal: merger pair recall 0.22 (D3) / 0.13 (MeSH) at precision 0.94/0.85. 312/366 concepts are unlinked. Labels are silver only, and labelling/human_check_sheet.csv was never filled. (2) Representative cases (activity 6). The report does not name the four cases (wireless backhaul, EPR steering, locally repairable code, holographic QCD) or interpret any of them: nothing on network position, neighbourhood, community path or disciplinary distribution, all of which the request asks for explicitly. (3) Community roles. 'Central in expanding communities' and 'form new thematic clusters' cannot be measured under the pre-declared rules (CORE_GROWING/FOUNDER never fire; wmz max -0.23), so these questions are unanswered, not 'done'. (4) Generality. The pool is about 90% physics/CS/materials/maths, grafting is null for physics, and no RQ2 analysis ran on MeSH beyond pattern frequencies.",
 "suggested_action": "Change the coverage table to Partial for activities 1, 5 and 6, and for the community-roles sub-question, with the reasons above. Add a 'Network substrate' paragraph: nodes are legacy concepts, the pool is attached, and a network built from the run's own grounded concepts was never constructed. Add a per-case subsection from art_QKsLguxnGFQT cases/*.json: concept name, cluster, origin, lead-lag category, roles along the alluvial path, and subfield shares at F+1 / onset / 2022. If budget allows, spend the next iteration's samples on the sealed folds and on biomedical RQ2 coverage, not on new indicators."},
{"category": "rigor", "severity": "major",
 "description": "TRACEABILITY OF MARKERS. Iteration-3 artifacts are cited as [ARTIFACT:gen_art_evaluation_1], [ARTIFACT:gen_art_experiment_5] ... [ARTIFACT:gen_art_experiment_8]. These are workspace folder names, not artifact IDs (art__i2cIye01VnN, art_htO_gJuUn6Pr, art_62TVG6A4f7Iy, art_2Cd2JJypeGuA, art_QKsLguxnGFQT), so the link-injection step cannot resolve them. Artifact 2 (the 259,716-work background sample, gen_art_dataset_2, the substrate of every co-word snapshot) is tagged [ARTIFACT:art_eR1Z7fMlOcxs], which is the iteration-2 hydrated dataset_5. The coverage table repeats the error for activity 2. In the run ledger, iteration-3 wall times and spend are blank, although the READMEs give them ($0; about 8 min / 15 min / 15 min on 4 CPUs).",
 "suggested_action": "Swap the five folder names for the artifact IDs. For Artifact 2, cite the workspace path iter_1/gen_art/gen_art_dataset_2, since it has no ID in the supplement, and fix the coverage row. Fill the ledger's iteration-3 rows ($0 OpenAlex/LLM; wall times from each README / logs/timings.json)."},
{"category": "evidence", "severity": "major",
 "description": "Several items the previous review named as MUST-FIX for exp_1-exp_4 are still missing. exp_2 (art_yjFB8Spw2w6M): the delta-R² MDE >= 0.03 (so Maillart's 0.018 cannot be detected), the wild-cluster CRV1 size correction 0.16 -> 0.07, origin cooling onsets 33/51/83 at theta 0.6/0.7/0.8, rho~ CI coverage 0.77, misspecification FDR 0.20-0.37, Spearman(rho~, momentum) 0.14, and the n_min 5/10 synthetic FDR (0.28). exp_3 (art_mbFjmo5rbbf8): primary-E accretion S -0.104 [-0.120,-0.016], Holm 0.003 (pilot); the statement that accretion is 'untested, not refuted' (rarefied Baselga NA 55%, MDE 1.4-2.1 SD); balance SMDs; centrality-gain ΔR² (precursors hurt: HGB -0.19 [-0.31,-0.05]); typology survivor bias (59 of 123 concepts); Leiden AMI 0.62-0.63; 63-79% of neighbourhoods denser than the degree-preserving null; reference-arm E rate 6%; logit rows for E (-0.028 [-0.094,0.019]) and E_alt (+0.051 [0.000,0.132]). exp_1 (art_BdBvbNuNU8E7): the baseline and ablation table (C-value 0.716, lexical-only 0.762, no-embeddings 0.774, HGB 0.815, LLM-B 0.773 with classifier +0.045 [0.006,0.085]); covariate-shift AUC 0.996; merger P/R and MeSH OOF AUC 0.75 below the >0.9 target. exp_4 (art_yWUkgWWKyq_h): the 9-row aligned block (only the E_up closure row is given); participation LEVEL +0.37 SD (BH q<0.001); rolling dAUC +0.041 [-0.050,0.098]; E_vol -0.009 [-0.016,-0.003] and E_cent -0.036 [-0.061,-0.015]. dataset_5: the failed first batch-equivalence attempt (authorship truncation at 100) and the credit ledger by step (P1 1,416 / P2 5,488 / P3 329 / checks 4).",
 "suggested_action": "Add these in place in the iteration-2 section, marked '[Added in iteration 3]'. Each value is already a row in art__i2cIye01VnN results/record_of_numbers.csv (flag MISSING_IN_REPORT), so they can be transcribed with source keys."},
{"category": "novelty", "severity": "major",
 "description": "The nearest-neighbour comparisons are one-sided. Cheng et al. 2023 (ASR 88:522-561; about 60k ideas, WoS 1993-2016) find that new ideas diffuse more when they are related to prominent concepts AND 'deeply situated within focused research discourses'. The report cites Cheng only as support for grafting. The 'focused discourses' result points toward cohesion, which is in tension with the openness-before-take-off reading, and the report does not discuss that tension. For grafting, the principle of relatedness is cited, but the report does not say that relatedness density was controlled, or what its coefficient was. Guevara et al. 2016's research-space result (entry into related fields) is the closest entry-level neighbour and is not compared. For the lead-lag and typology claims, no published neighbour is named at all (e.g. Rotolo et al. 2015 on emerging-technology attributes; Salatino et al. 2017 on pre-emergence cross-fertilisation, which predicts cross-community connectivity from the start). So the positive RQ2 findings have not yet earned novelty credit in this record.",
 "suggested_action": "For each positive claim (closure/openness, host-native grafting, the k=2 typology, expansion-before-diffusion), add a two-line 'nearest neighbour -> what this run adds -> where it disagrees' entry. Include the Cheng et al. focused-discourse tension explicitly, and report the RD control coefficient from d2_models.json."},
{"category": "evidence", "severity": "minor",
 "description": "Smaller traceability and labelling slips. Table 13's 'S_raw -0.758' is the complete-case S_raw_cc; the full-sample S_raw differs. 'Fresh replication on 100 new concepts' should give n_matched = 14 and note that 124 new concepts were attached. Table 17's 'Dominant origin: Mixed' hides the counts (broad: CS 21, Physics 22, Engineering 8, Materials 7, Maths 6 of 66; localised: Physics 76 of 136). 'Holm p = 1e-5' is 1.3e-5 (CRV1 p 6.4e-6). The MeSH SENS1 dP correction the previous review requested was handled by deleting the sentence rather than correcting it. Graft-label establishment 0.44 vs 0.20 is on 288 vs 1,458 MAIN screen entries, while the '15%' anchored share is on 2,215 SENSITIVITY entries.",
 "suggested_action": "Label S_raw_cc; add n_matched and denominators; give the origin counts per cluster from typology.json crosstabs.origin_group; restore the MeSH dP sentence with the corrected value."}
],
"results_reported": True,
"coverage": "partial",
"blocking": False,
"score": 5,
"confidence": 4
}
out.write_text(json.dumps(review, indent=2, ensure_ascii=False))
print("ok", len(review["critiques"]))
